# Generated by Django 4.2.5 on 2023-09-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place1',
            new_name='team',
        ),
    ]
